import { describe, expect, it } from "vitest";
import { parsePatch, type PatchFile } from "../../../shared/diff/patch";
import type { ReviewLayer } from "../../../shared/review";
import { generatedFolds, initialFolds, isMachineWritten, skimFolds } from "./initial-folds";

// The fold heuristic, one rule at a time. It is worth testing this way and only this way: the
// whole argument for folding anything without being asked is that the rules are few and each
// one is obviously right, so each one gets a case that would fail if it stopped being.
//
// Pure in, pure out — parsed patch files and layers. No store, no document, no fs.

/** One added file, from its literal new-side lines. The named fixtures in
 * `shared/diff/fixtures.ts` are all hand-written source, which is exactly what these rules
 * must *not* fire on; the content rules need a file whose first lines are the test's point. */
function added(path: string, lines: readonly string[]): string {
  return [
    `diff --git a/${path} b/${path}`,
    "new file mode 100644",
    "index 0000000..1111111",
    "--- /dev/null",
    `+++ b/${path}`,
    `@@ -0,0 +1,${lines.length} @@`,
    ...lines.map((line) => `+${line}`),
    "",
  ].join("\n");
}

function filesOf(...patches: readonly string[]): PatchFile[] {
  return parsePatch(patches.join(""), "initial-folds-test");
}

function fileAt(path: string, lines: readonly string[]): PatchFile {
  const [file] = filesOf(added(path, lines));
  if (file === undefined) {
    throw new Error(`fixture did not parse: ${path}`);
  }
  return file;
}

const PLAIN = ["export const x = 1;", "export const y = 2;"];

describe("isMachineWritten", () => {
  it("leaves hand-written source alone — the rule that matters most", () => {
    expect(isMachineWritten(fileAt("src/app.ts", PLAIN))).toBe(false);
    // A name that merely *mentions* one of the rules is not the rule: `lockfile.ts` is
    // source about lockfiles, and `sitemap.ts` ends in "map" only as a word.
    expect(isMachineWritten(fileAt("src/lockfile.ts", PLAIN))).toBe(false);
    expect(isMachineWritten(fileAt("src/sitemap.ts", PLAIN))).toBe(false);
  });

  it("folds a lockfile, by suffix or by the names that spell it differently", () => {
    for (const path of [
      "bun.lock",
      "Cargo.lock",
      "packages/api/poetry.lock",
      "gradle.lockfile",
      "package-lock.json",
      "pnpm-lock.yaml",
      "go.sum",
    ]) {
      expect(isMachineWritten(fileAt(path, PLAIN)), path).toBe(true);
    }
  });

  it("folds a source map and a minified bundle by name", () => {
    expect(isMachineWritten(fileAt("dist/app.js.map", PLAIN))).toBe(true);
    expect(isMachineWritten(fileAt("dist/app.min.js", PLAIN))).toBe(true);
    expect(isMachineWritten(fileAt("dist/styles.min.css", PLAIN))).toBe(true);
  });

  it("folds a one-line file whose one line is a bundle, whatever it is called", () => {
    expect(isMachineWritten(fileAt("dist/bundle.js", ["x".repeat(501)]))).toBe(true);
    // The threshold protects the ordinary one-line file: a config, a re-export, a version
    // string. Only *both* halves — one line, and an absurd one — mean minified.
    expect(isMachineWritten(fileAt("src/version.ts", ['export const VERSION = "1.2.3";']))).toBe(
      false,
    );
    // Two long lines is prose, not a bundle: a markdown paragraph is one long line per
    // paragraph, and folding someone's writing would be the worst miss this rule could make.
    expect(isMachineWritten(fileAt("docs/notes.md", ["p".repeat(600), "q".repeat(600)]))).toBe(
      false,
    );
  });

  it("folds a file whose head declares itself generated, in any of the three spellings", () => {
    expect(isMachineWritten(fileAt("src/api.ts", ["// @generated by codegen", ...PLAIN]))).toBe(
      true,
    );
    expect(
      isMachineWritten(
        fileAt("src/pb.go", ["// Code generated by protoc. DO NOT EDIT.", ...PLAIN]),
      ),
    ).toBe(true);
    expect(isMachineWritten(fileAt("src/schema.sql", ["-- DO NOT EDIT", ...PLAIN]))).toBe(true);
  });

  it("does not read a marker out of the middle of a file", () => {
    // Only the head is searched, and only as far as the diff shows it. Further down, "DO NOT
    // EDIT" is a sentence in someone's comment about a constant, not a claim about the file.
    const deep = ["a", "b", "c", "d", "e", "f", "// DO NOT EDIT this constant by hand", "g"];
    expect(isMachineWritten(fileAt("src/config.ts", deep))).toBe(false);
  });

  it("matches the marker case-sensitively, so prose about editing is still prose", () => {
    expect(isMachineWritten(fileAt("README.md", ["Please do not edit the generated files."]))).toBe(
      false,
    );
  });
});

describe("generatedFolds", () => {
  it("answers the machine-written paths in diff order and nothing else", () => {
    const files = filesOf(
      added("src/app.ts", PLAIN),
      added("bun.lock", PLAIN),
      added("src/api.ts", ["// @generated", ...PLAIN]),
    );
    expect(generatedFolds(files)).toEqual(["bun.lock", "src/api.ts"]);
  });
});

/** A flat layer array the way `flattenLayers` stamps one: document order, `parent` naming the
 * layer above. Written by hand here so a test can say "this child hangs off that skim parent"
 * without going through an artifact. */
function layer(
  id: string,
  ranges: readonly string[],
  extra: Partial<ReviewLayer> = {},
): ReviewLayer {
  return {
    id,
    label: id,
    ranges: ranges.map((file) => ({ file, side: "additions" as const, startLine: 1, endLine: 2 })),
    ...extra,
  };
}

describe("skimFolds", () => {
  const files = filesOf(
    added("src/app.ts", PLAIN),
    added("src/gen.ts", PLAIN),
    added("docs/notes.md", PLAIN),
  );

  it("folds a file only its skim layer claims", () => {
    const layers = [layer("real", ["src/app.ts"]), layer("mech", ["src/gen.ts"], { skim: true })];
    expect(skimFolds(files, layers)).toEqual(["src/gen.ts"]);
  });

  it("leaves a file alone when a real chapter also claims it", () => {
    // The rule is "every layer claiming it", not "some layer": a file a real chapter explains
    // is a file the review asks to be read, and folding it would hide the explained part.
    const layers = [
      layer("real", ["src/app.ts", "src/gen.ts"]),
      layer("mech", ["src/gen.ts"], { skim: true }),
    ];
    expect(skimFolds(files, layers)).toEqual([]);
  });

  it("carries the mark down to a skim layer's children", () => {
    // A grouping layer has no ranges of its own, so ownership can never land on it. If the
    // mark did not inherit, marking a group mechanical would do nothing at all.
    const layers = [
      layer("group", [], { skim: true }),
      layer("child", ["src/gen.ts"], { parent: "group" }),
    ];
    expect(skimFolds(files, layers)).toEqual(["src/gen.ts"]);
  });

  it("says nothing about a file no layer claims", () => {
    // The uncovered remainder is the coverage gate's business, not the fold heuristic's:
    // unclaimed is not the same as mechanical.
    expect(skimFolds(files, [layer("mech", ["src/gen.ts"], { skim: true })])).toEqual([
      "src/gen.ts",
    ]);
    expect(skimFolds(files, [])).toEqual([]);
  });
});

describe("initialFolds", () => {
  it("is the union of both rule sets, in diff order, without repeats", () => {
    const files = filesOf(
      added("src/app.ts", PLAIN),
      added("bun.lock", PLAIN),
      added("src/gen.ts", PLAIN),
    );
    // `bun.lock` is claimed by the skim layer *and* caught by the heuristic — one entry.
    const layers = [
      layer("real", ["src/app.ts"]),
      layer("mech", ["bun.lock", "src/gen.ts"], { skim: true }),
    ];
    expect(initialFolds(files, layers)).toEqual(["bun.lock", "src/gen.ts"]);
  });

  it("works on a session with no layers at all — the plain repo case", () => {
    // The whole reason the heuristic exists beside `skim`: a repository opened with ⌘O has no
    // artifact, no layers and the same 2,000-line lockfile in the middle of its diff.
    const files = filesOf(added("src/app.ts", PLAIN), added("pnpm-lock.yaml", PLAIN));
    expect(initialFolds(files, [])).toEqual(["pnpm-lock.yaml"]);
  });
});
