import type { PatchFile } from "../../../shared/diff/patch";
import { filesByAnchorPath } from "../../../shared/diff/patch";
import { walkFileLines } from "../../../shared/diff/walk";
import { layerOutline } from "../../../shared/layers";
import type { ReviewLayer } from "../../../shared/review";

// Which files open folded the first time a session sees its diff — the lockfile, the
// generated client, the source map, and whatever the review's author marked `skim`.
//
// Two sources, one answer, and they are not interchangeable. `skimFolds` reads the
// *artifact*: an author who marked a layer skim has said, about this change, that there is
// nothing in those files to read. `generatedFolds` reads the *diff*: it is what the app can
// work out on its own, which is the only thing available to a plain repo session — no
// layers, no artifact, and exactly the same 2,000-line lockfile sitting between two files
// the reader cares about. Neither subsumes the other, so both run and the union is seeded.
//
// Pure, node-free, DOM-free, and one exported function per rule set, because the whole
// argument for folding anything by default is that the rules are few and inspectable. A
// heuristic nobody can read is a heuristic nobody can correct.
//
// **Folding is presentation, never omission.** A folded file is a header band with a
// disclosure: it is still in the diff, still in the tree, still reachable by `j`/`k`, still
// anchorable, and still counted in the read tally. Nothing here removes anything, and
// nothing here marks anything read.

/** How many lines from the top of the new side a generated-file marker may hide in. Five,
 * because every convention that exists puts it in the file's first comment block — Go's
 * `// Code generated ... DO NOT EDIT.`, protobuf's header, `@generated` — and searching
 * further down starts matching prose that merely *mentions* editing. Only the lines the
 * patch actually shows are searched: a diff that starts at line 200 has no head to read,
 * and the file simply does not match. */
const GENERATED_HEAD_LINES = 5;

/** The markers themselves, matched case-sensitively and as substrings. Case-sensitive
 * because `DO NOT EDIT` shouting in a header is the convention and "do not edit" in a
 * sentence is not; substrings because each one appears inside a comment whose surrounding
 * syntax is the generator's business, not ours. */
const GENERATED_MARKERS = ["@generated", "DO NOT EDIT", "Code generated by"];

/** Lock files whose name is the whole signal. The `.lock`/`.lockfile` suffix covers most
 * ecosystems (Cargo, Gemfile, poetry, composer, flake, mix, pubspec, Pipfile, uv, bun,
 * yarn); these are the ones that spell it some other way. */
const LOCK_FILE_NAMES = new Set([
  "package-lock.json",
  "npm-shrinkwrap.json",
  "pnpm-lock.yaml",
  "bun.lockb",
  "go.sum",
  "packages.lock.json",
]);

/** Past this, one line is not a line anyone reads — it is a bundle. Deliberately generous:
 * the rule only fires on a file whose *entire* new side is that one line, so the threshold
 * is there to spare a one-line config or a single long import, not to judge line length. */
const MINIFIED_LINE_LENGTH = 500;

/** The path's last segment. Every name rule below is about the file, not where it sits. */
function baseName(path: string): string {
  return path.split("/").at(-1) ?? path;
}

function isLockFile(name: string): boolean {
  return LOCK_FILE_NAMES.has(name) || name.endsWith(".lock") || name.endsWith(".lockfile");
}

/** A source map: build output whose whole content is a coordinate table. */
function isSourceMap(name: string): boolean {
  return name.endsWith(".map");
}

/** `app.min.js`, `styles.min.css` — the name says the content is compiled, whatever the
 * extension after it. */
function isMinifiedName(name: string): boolean {
  return /\.min\.[0-9a-z]+$/iu.test(name);
}

/** A new side that is one line, and a long one: a minified bundle that did not say so in
 * its name. `additionLines` is every context and addition line the patch carried for the
 * new side (see `@pierre/diffs`' `FileDiffMetadata`), so exactly one entry means the file
 * has exactly one line — not that the diff only showed one. */
function isSingleLongLine(file: PatchFile): boolean {
  const lines = file.fileDiff.additionLines;
  return lines.length === 1 && (lines[0]?.length ?? 0) > MINIFIED_LINE_LENGTH;
}

/** Whether the top of the new side declares itself generated. Walks only as far as
 * `GENERATED_HEAD_LINES` — hunks are in ascending order, so the first new-side line past
 * the limit ends the walk and a 40,000-line generated file costs five string reads. */
function declaresGenerated(file: PatchFile): boolean {
  const texts = file.fileDiff.additionLines;
  let found = false;
  walkFileLines(file.fileDiff, (line) => {
    if (line.side !== "additions") {
      return true;
    }
    if (line.lineNumber > GENERATED_HEAD_LINES) {
      return false;
    }
    const text = texts[line.index] ?? "";
    if (GENERATED_MARKERS.some((marker) => text.includes(marker))) {
      found = true;
      return false;
    }
    return true;
  });
  return found;
}

/** Whether this one file reads as machine-written. Exported for the rule-by-rule test and
 * for anything that wants the question about a single file; `generatedFolds` is the answer
 * over a whole diff. */
export function isMachineWritten(file: PatchFile): boolean {
  const name = baseName(file.path);
  return (
    isLockFile(name) ||
    isSourceMap(name) ||
    isMinifiedName(name) ||
    isSingleLongLine(file) ||
    declaresGenerated(file)
  );
}

/** The diff's own machine-written files, in diff order. What a plain repo session folds,
 * and half of what a review session folds. */
export function generatedFolds(files: readonly PatchFile[]): string[] {
  return files.filter((file) => isMachineWritten(file)).map((file) => file.path);
}

/** The files every layer claiming them marked `skim` — the author's half.
 *
 * "Every layer claiming them", not "some layer": a file the mechanical chapter lists *and*
 * a real chapter explains is a file the review asks the reader to read, and folding it
 * would hide the part that was explained. Claiming is by a layer's **own** ranges, since
 * that is where ownership lives everywhere else (`layerOwning`); a grouping layer carries
 * none and so claims nothing, which is why the mark is inherited down instead — a skim
 * parent means every section under it is skim, exactly as its extent is theirs.
 *
 * Resolved through `filesByAnchorPath` so a range authored against a file's pre-rename path
 * still lands on the file that carries it today, the same way a comment does. */
export function skimFolds(files: readonly PatchFile[], layers: readonly ReviewLayer[]): string[] {
  const byAnchorPath = filesByAnchorPath(files);
  const allSkim = new Map<string, boolean>();
  for (const entry of layerOutline(layers)) {
    const skim =
      entry.layer.skim === true || entry.ancestors.some((ancestor) => ancestor.skim === true);
    for (const range of entry.layer.ranges) {
      const file = byAnchorPath.get(range.file);
      if (file === undefined) {
        continue;
      }
      allSkim.set(file.path, (allSkim.get(file.path) ?? true) && skim);
    }
  }
  return files.filter((file) => allSkim.get(file.path) === true).map((file) => file.path);
}

/** Everything a session folds on its first loaded diff: the union of the two rule sets, in
 * diff order and without duplicates. The one function the store calls, so "what gets seeded"
 * is a single answer rather than two call sites that could fall out of step.
 *
 * A review session runs both halves — an author can mark a hand-written migration `skim`,
 * and a `bun.lock` nobody put in a layer is still a lockfile. */
export function initialFolds(
  files: readonly PatchFile[],
  layers: readonly ReviewLayer[],
): string[] {
  const folded = new Set([...generatedFolds(files), ...skimFolds(files, layers)]);
  return files.filter((file) => folded.has(file.path)).map((file) => file.path);
}
